### ISSUE TITLE
Question: API Key Authentication

### ISSUE THREAD

**Issue by grandant** [entaseteam/api.v2.docs#1]
Здравейте,

Казвам се Петър Бозуков и преди време говорихме по телефона. Сайта ви изглежда супер, поздрави за добре свършената работа. Аз работя за ДКТ Шумен и бих искал да получа АПИ ключ. Имейла ми е bozukov.p@gmail.com Благодаря ви предварително.

**Comment by skito** [comment]
Здравейте,  заявката е обработена.

**Comment by grandant** [comment]
Привет,

Опитвам се да се свържа по телефона и чрез имейл, но безуспешно. Изглежда мейла, на който съм ви писал преди таймаутва:

<img width="790" height="446" alt="Image" src="https://github.com/user-attachments/assets/c87208f9-c308-4b4d-8236-7f59231e2e5f" />

Ще ми трябва АПИ ключ и за акаунта на МДТ Велико Търново.

Благодаря предварително.

**Comment by entaseteam** [comment]
Hi @grandant ,

To reach the support team, please use the question mark icon in your Entase dashboard (top right corner).
https://howto.entase.com/organizers/personal-account/layout-preferences

FYI: Entase operates only by the domain entase.com

**Comment by grandant** [comment]
Hi @entaseteam,

Thanks. Ticket sent.
